[package]
name = "lore-seeker"
version = "0.0.1"
authors = ["Fenhl <fenhl@fenhl.net>"]

[[bin]]
name = "lore-seeker"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
itertools = "*"
native-windows-gui = "0.2.0"
open = "*"
reqwest = "*"
serde = "1.0"
serde_derive = "1.0"
urlencoding = "*"
